import type { CoverageReport } from './coverage';
import { isReadOnly } from './coverage';
import type { Finding } from './rules';
import type { ResourceModel } from './nodeModel';
import { operationId } from './nodeModel';

const escapeCell = (value: string): string => value.replace(/\|/g, '\\|');

const percentage = (part: number, total: number): string =>
	total === 0 ? '—' : `${Math.round((part / total) * 100)}%`;

const coverageSection = (resources: ResourceModel[], coverage: CoverageReport): string[] => {
	const lines: string[] = ['## Test coverage', ''];

	const total = coverage.entries.length;
	const covered = coverage.entries.filter((entry) => entry.tests.length > 0).length;
	const writes = coverage.entries.filter((entry) => isReadOnly(entry.operation) === false);
	const coveredWrites = writes.filter((entry) => entry.tests.length > 0).length;

	lines.push(
		`${covered} of ${total} operations are referenced by an integration test (${percentage(covered, total)}).`,
		`Side-effecting operations: ${coveredWrites} of ${writes.length} covered (${percentage(coveredWrites, writes.length)}).`,
		'',
		'| Resource | Operations | Covered | Uncovered writes |',
		'| --- | --- | --- | --- |',
	);

	for (const resource of resources) {
		const entries = coverage.entries.filter((entry) => entry.operation.resource === resource.name);
		const resourceCovered = entries.filter((entry) => entry.tests.length > 0).length;
		const uncoveredWrites = entries.filter(
			(entry) => entry.tests.length === 0 && isReadOnly(entry.operation) === false,
		).length;

		lines.push(
			`| ${escapeCell(resource.name)} | ${entries.length} | ${resourceCovered} (${percentage(resourceCovered, entries.length)}) | ${uncoveredWrites} |`,
		);
	}

	lines.push('', '### Operation detail', '', '| Operation | Kind | Tests |', '| --- | --- | --- |');

	for (const entry of coverage.entries) {
		const kind = isReadOnly(entry.operation) ? 'read' : 'write';
		const tests = entry.tests.length > 0 ? entry.tests.join(', ') : '**none**';
		lines.push(`| ${escapeCell(operationId(entry.operation))} | ${kind} | ${escapeCell(tests)} |`);
	}

	if (coverage.orphanedReferences.length > 0) {
		lines.push(
			'',
			'### Tests referencing unknown operations',
			'',
			'These tests name a resource/operation pair the node no longer exposes — likely a rename.',
			'',
			'| Reference | Tests |',
			'| --- | --- |',
		);

		for (const orphan of coverage.orphanedReferences) {
			lines.push(`| ${escapeCell(orphan.reference)} | ${escapeCell(orphan.tests.join(', '))} |`);
		}
	}

	return lines;
};

const lintSection = (findings: Finding[], baseline: Set<string>): string[] => {
	const lines: string[] = ['## UX consistency', ''];

	if (findings.length === 0) {
		lines.push('No findings.', '');
		return lines;
	}

	const byRule = new Map<string, Finding[]>();
	for (const item of findings) {
		byRule.set(item.rule, [...(byRule.get(item.rule) ?? []), item]);
	}

	lines.push('| Rule | Severity | Findings | New |', '| --- | --- | --- | --- |');

	for (const [rule, items] of Array.from(byRule.entries()).sort((a, b) =>
		a[0].localeCompare(b[0]),
	)) {
		const fresh = items.filter((item) => baseline.has(item.id) === false).length;
		lines.push(`| ${rule} | ${items[0].severity} | ${items.length} | ${fresh} |`);
	}

	for (const [rule, items] of Array.from(byRule.entries()).sort((a, b) =>
		a[0].localeCompare(b[0]),
	)) {
		lines.push('', `### ${rule}`, '');
		for (const item of items) {
			const marker = baseline.has(item.id) ? '' : ' _(new)_';
			lines.push(`- \`${item.scope}\` — ${item.message}${marker}`);
		}
	}

	return lines;
};

export const renderReport = ({
	resources,
	coverage,
	findings,
	baseline,
}: {
	resources: ResourceModel[];
	coverage: CoverageReport;
	findings: Finding[];
	baseline: Set<string>;
}): string =>
	[
		'# Operation quality report',
		'',
		'<!-- Generated by `pnpm run test:quality`. Do not edit by hand. -->',
		'',
		...coverageSection(resources, coverage),
		'',
		...lintSection(findings, baseline),
		'',
	].join('\n');
